name = "ep-4-ch-1"

[dev-dependencies]
test-drive.git = "https://github.com/fortran-lang/test-drive"
test-drive.tag = "v0.5.0"

[[test]]
name = "test_matrix_transforms"
source-dir = "test"
main = "main.f90"
